// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgCOMy7tSKAv75DMHcGYivaAT7d4_Mlw',
    appId: '1:548445077818:web:0b33efba12245c4aa19003',
    messagingSenderId: '548445077818',
    projectId: 'flutterchat-e1738',
    authDomain: 'flutterchat-e1738.firebaseapp.com',
    storageBucket: 'flutterchat-e1738.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKLY5pYJpLnWfYiZcNjEkWG7YALTBS6EU',
    appId: '1:548445077818:android:4deeea258827e321a19003',
    messagingSenderId: '548445077818',
    projectId: 'flutterchat-e1738',
    storageBucket: 'flutterchat-e1738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBKBgNvXckmcDaGlKRFAucDZ13DOD_pBg',
    appId: '1:548445077818:ios:846489e67b9b7686a19003',
    messagingSenderId: '548445077818',
    projectId: 'flutterchat-e1738',
    storageBucket: 'flutterchat-e1738.firebasestorage.app',
    iosBundleId: 'com.chethankrishna.chat',
  );
}
